KAW-7695 Add table block
Netcentric/edge-delivery-bimota pull request #12
Opened 2024-08-06 07:27 UTC by TomaszDziezykNetcentric

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--edge-delivery-bimota--netcentric.hlx.page/
- After: https://kaw-7695-table--edge-delivery-bimota--netcentric.hlx.page/

2024-08-06 08:37 UTC, lakshmishriaswathnarayana requested changes

2024-08-06 08:37 UTC, lakshmishriaswathnarayana commented on blocks/table/table.css
> +  background-color: #fff;
can you use variable here?

2024-08-06 14:52 UTC, lakshmishriaswathnarayana requested changes
Since you have handle this component using table, can you also handle [this](https://bimota.it/cookie-policy/) as variant

2024-08-07 09:17 UTC, TomaszDziezykNetcentric commented on blocks/table/table.css
> +  background-color: #fff;
done

2024-08-07 09:17 UTC, TomaszDziezykNetcentric commented
> Since you have handle this component using table, can you also handle [this](https://bimota.it/cookie-policy/) as variant

done

2024-08-07 09:51 UTC, lakshmishriaswathnarayana approved these changes

2024-08-07 09:51 UTC, merged