KAW-7944: vehicle selector component
Netcentric/edge-delivery-bimota pull request #42
Opened 2024-10-10 07:26 UTC by IoanaOrca

[Issue](https://projects.netcentric.biz/browse/KAW-7944)

Fix #<gh-issue-id>

Test URLs:
- Before: https://redesign-develop--edge-delivery-bimota--netcentric.hlx.page/drafts/ioana/vehicle-selector
- After: https://KAW-7944-vehicle-selector--edge-delivery-bimota--netcentric.hlx.page/drafts/ioana/vehicle-selector

2024-10-14 07:53 UTC, lakshmishriaswathnarayana approved these changes

2024-10-14 11:58 UTC, TomaszDziezykNetcentric requested changes

2024-10-14 11:58 UTC, TomaszDziezykNetcentric commented on blocks/vehicle-selector/vehicle-selector.css
> +@media screen and (width >= 1024px) {
Should be `1025px`

2024-10-14 11:58 UTC, TomaszDziezykNetcentric commented on blocks/vehicle-selector/vehicle-selector.js
> +    // TODO make surer i target the right heading
What does it mean? Can you implement it? Or if it is not needed remove the comment.

2024-10-14 11:58 UTC, TomaszDziezykNetcentric commented on blocks/vehicle-selector/vehicle-selector.js
> +  }, 50);
Why do we need the timeout here? The 50ms delay will not be visible to the user. If the `setTimeout` is needed here for another reason, please add a suitable comment in the code.

2024-10-16 06:41 UTC, TomaszDziezykNetcentric approved these changes

2024-10-16 12:48 UTC, merged